#!/bin/sh

SILENT="0"

output(){
    [ "x$SILENT" = "x0" ] && echo $@
}

if [ -f "/etc/issue" ]; then
    output "Hummingbird - `cat /etc/issue`"
else
    output "Hummingbird initializing system"
fi

output " ... Mounting api directories"

mountpoint -q /proc ||
    mount -t proc proc /proc -o nosuid,noexec,nodev
mountpoint -q /sys ||
    mount -t sysfs sys /sys -o nosuid,noexec,nodev
mountpoint -q /run ||
    mount -t tmpfs run /run -o mode=0755,nosuid,nodev
mountpoint -q /dev ||
    mount -t devtmpfs dev /dev -o mode=0755,nosuid

mkdir -p -m0755 /dev/{pts,shm} /run/lock

mountpoint -q /dev/pts ||
    mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
mountpoint -q /dev/shm ||
    mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

mountpoint -q /sys/fs/cgroup ||
    mount -n -t cgroup nodev /sys/fs/cgroup

IFS='
'
for cgroup in `awk '$4 == 1' /proc/cgroups`; do
    cgroup=`echo $cgroup | awk '{print $1}'`
    mountpoint -q /sys/fs/cgroup/$cgroup || {
        mkdir -p /sys/fs/cgroup/$cgroup
        mount -t cgroup cgroup /sys/fs/cgroup/$cgroup -o $cgroup
    }
done
unset IFS

output " ... Setting up udev"

# TODO: don't require systemd (this is only because it's what I had
# on my machine at the time of writing this up)
/lib/systemd/systemd-udevd --daemon 2>1 > /dev/null
udevadm trigger --action=add --type=subsystems
udevadm trigger --action=add --type=devices
udevadm settle

output " ... Mounting root filesystem"
# TODO: support for other filesystems (btrfs, zfs, etc)
mount -o remount,rw /

output " ... Activating swap"
swapon -a

output " ... Setting hostname"
cat /etc/hostname >| /proc/sys/kernel/hostname

output " ... Setting up loopback"
ip link set up dev lo

output " ... Setting up sysctl"
sysctl --system > /dev/null

# Set random seed

if [ -f "/etc/rc.local" ]; then
    output " ... Running /etc/rc.local"
    sh /etc/rc.local
fi

output " ... Starting TTYs"

respawn(){
    (while :; do
        eval $1
    done)
}

for index in `seq 1 8`; do
    respawn "agetty 115200,38400,9600 tty${index} linux"
done

sleep infinity
